# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'kategorija',
                'verbose_name_plural': 'kategorije',
            },
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('creator', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'vic',
                'verbose_name_plural': 'vicevi',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.Joke')),
            ],
            options={
                'verbose_name': 'lajk',
                'verbose_name_plural': 'lajkovi',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('device_id', models.CharField(max_length=100)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.Joke')),
            ],
            options={
                'verbose_name': 'ocena',
                'verbose_name_plural': 'ocene',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('joke', 'device_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('joke', 'device_id')]),
        ),
    ]
